branches:
    only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
    global:
        - JULIA_DEBUG="all"
    matrix:
        - COMPILED_MODULES="no" INLINE="no"
        - COMPILED_MODULES="no" INLINE="yes"
        - COMPILED_MODULES="yes" INLINE="no"
        - COMPILED_MODULES="yes" INLINE="yes"

git:
    depth: 99999999

julia:
    - 1.1

language: julia

matrix:
    allow_failures:
        - julia: "nightly"
        - os: osx
    fast_finish: true

notifications:
    email:
        on_success: never # default: change
        on_failure: always # default: always

os:
    - linux
#     - osx

############################################################################

script: ./ci/travis/script.sh
