branches:
    only:
        - master
        - staging
        - trying
        - /^release\/.*$/ # release branches
        - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

git:
    depth: 99999999

julia:
    - 1.1

language: julia

matrix:
    allow_failures:
        - julia: "nightly"
        - os: osx
    fast_finish: true

notifications:
    email:
        on_success: never # default: change
        on_failure: always # default: always

os:
    - linux
    # - osx

############################################################################

# script: ./ci/travis/script.sh

before_install:
    - true
install:
    - true
before_script:
    - true
script:
    - true
after_script:
    - true

############################################################################

stages:
    - "Benchmark"
    - "Test"
    # - "Benchmark"

############################################################################

jobs:
    include:
        - stage: "Test"
          os: linux
          julia: 1.1
          env:
              - JULIA_DEBUG="all"
              - COMPILED_MODULES="no"
              - INLINE="no"
          script: ./ci/travis/script.sh
        - stage: "Test"
          os: linux
          julia: 1.1
          env:
              - JULIA_DEBUG="all"
              - COMPILED_MODULES="no"
              - INLINE="yes"
          script: ./ci/travis/script.sh
        - stage: "Test"
          os: linux
          julia: 1.1
          env:
              - JULIA_DEBUG="all"
              - COMPILED_MODULES="yes"
              - INLINE="no"
          script: ./ci/travis/script.sh
        - stage: "Test"
          os: linux
          julia: 1.1
          env:
              - JULIA_DEBUG="all"
              - COMPILED_MODULES="yes"
              - INLINE="yes"
          script: ./ci/travis/script.sh
        - stage: "Benchmark"
          os: linux
          julia: 1.1
          script: ./ci/travis/benchmark.sh
          # script: true
