name = "ModelSanitizer"
uuid = "913cd07a-ab48-11e9-38cf-61416429a70b"
authors = ["Dilum Aluthge <dilum@aluthge.com>"]
version = "0.1.0-DEV"

[compat]
DataFrames = "^0.18.4"
MLJ = "^0.2.5"
MLJBase = "^0.2.3"
MLJModels = "^0.2.5"
MultivariateStats = "^0.6.0"
julia = "^1.1.0"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "MLJ", "MLJBase", "MLJModels", "MultivariateStats", "Test"]
